version: "3.6"

networks:
  inside:
    driver: bridge

volumes:
  dbdata:
    driver: local

services:
  db:
    image: mariadb:10.2
    env_file:
      - .env
    container_name: "ojs_db_${COMPOSE_PROJECT_NAME:-demo}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ojsPwd}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-ojs}"
      MYSQL_USER: "${MYSQL_USER:-ojs}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-ojsPwd}"
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - inside
    restart: always

  ojs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: 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
    env_file:
      - .env
    container_name: "ojs_app_${COMPOSE_PROJECT_NAME:-demo}"
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - .:/var/www/html
      # - ./docker/volumes/private:/var/www/files
      # - ./docker/volumes/public:/var/www/html/public
#      # WARNING: You can only enable file-volumes if file exists in the container.
#      - ./volumes/config/ojs.config.inc.php:/var/www/html/config.inc.php
#      - ./volumes/config/apache.htaccess:/var/www/html/.htaccess
#      - ./volumes/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - inside
    depends_on:
      - db
    restart: always
